---
# defaults file for supporting_infrastructure

vpc_cidr_block: 192.168.4.0/23
private_subnet_cidr_block: 192.168.4.0/24
public_subnet_cidr_block: 192.168.5.0/24

bastion_private_ip: 192.168.5.200
support_private_ip: 192.168.4.10
registry_private_ip: 192.168.4.15

bootstrap_private_ip: 192.168.4.20
master_private_ips:
  - 192.168.4.200
  - 192.168.4.201
  - 192.168.4.202
worker_private_ips:
  - 192.168.4.100
  - 192.168.4.101

openshift_hostname: "{{ cluster_name }}.{{ base_domain }}"

cluster_id: "{{ openshift_hostname | replace('.', '-') }}"

terraform_bucket: "{{ cluster_id }}-tf"

supporting_infra_repos_dir: /repos
supporting_infra_rpms:
  - docker
  - haproxy
  - dnsmasq
