---

- name: Disable DNS lookup on SSH connections
  lineinfile:
    path: /etc/ssh/sshd_config
    line: UseDNS no
  become: yes
  register: r_supporting_infra_ssh_usedns_no

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
  when: r_supporting_infra_ssh_usedns_no.changed
