---

- name: Create YUM repository
  yum_repository:
    name: internal
    description: Internal
    baseurl: http://{{ bastion_private_ip }}/repos/
    enabled: yes
    gpgcheck: no
    state: present
  become: yes

- name: Install required packages
  yum:
    name:
      - dnsmasq
      - haproxy
    disablerepo: "*"
    enablerepo: internal
    state: present
  become: yes

- name: Create dnsmasq config file
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/openshift.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  register: r_supporting_infra_dnsmasq_conf

- name: Start and enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
  become: yes

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: yes
  when: r_supporting_infra_dnsmasq_conf.changed

- name: Create haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  register: r_supporting_infra_haproxy_conf

- name: Start and enable haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted
  become: yes
  when: r_supporting_infra_haproxy_conf.changed
